name: Deploy App Service
description: Deploys an image to an Azure app service

inputs:
  web-app-settings:
    description: Optional app settings JSON to apply to web app before deployment
    required: false
  web-app-name:
    description: Name of web app to deploy to, leave empty for no deploy
    type: string
    default: ''
  image-tag:
    description: Tag of image to deploy to app service
    type: string
    required: true

runs:
  using: composite

  steps:
    - name: Log in to Azure CLI
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZ_CLIENT_ID }}
        tenant-id: ${{ env.AZ_TENANT_ID }}
        subscription-id: ${{ env.AZ_SUBSCRIPTION_ID }}

    - name: Optional set web app settings (Dev)
      if: inputs.web-app-settings != ''
      uses: Azure/appservice-settings@v1
      with:
       app-name: ${{ env.RESOURCE_NAME_PREFIX }}-${{ inputs.web-app-name }}
       app-settings-json: '${{ inputs.web-app-settings }}'

    - name: Optional deploy web app (Dev)
      if: inputs.web-app-name != ''
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.web-app-name }}
        images: "${{ inputs.image-tag }}"
