project_code = "s205"
moodle_site_fullname = "Social Work Induction Programme"
moodle_site_shortname = "SWIP"
webapp_storage_account_name = "webappsa"
parent_business_tag = "Children and Families"
product_tag = "Social Work Induction Programme"
service_offering_tag = "Social Work Induction Programme"
