// <auto-generated />
using System;
using System.Text.Json;
using Dfe.Sww.Ecf.Core.DataStore.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dfe.Sww.Ecf.Core.DataStore.Postgres.Migrations
{
    [DbContext(typeof(EcfDbContext))]
    [Migration("20240722163707_cleanup-redundant-auth-code")]
    partial class cleanupredundantauthcode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.Establishment", b =>
                {
                    b.Property<Guid>("EstablishmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address3")
                        .UseCollation("case_insensitive");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("county")
                        .UseCollation("case_insensitive");

                    b.Property<string>("EstablishmentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("establishment_name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("EstablishmentNumber")
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("establishment_number")
                        .IsFixedLength();

                    b.Property<int?>("EstablishmentStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_status_code");

                    b.Property<string>("EstablishmentStatusName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("establishment_status_name");

                    b.Property<string>("EstablishmentTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("establishment_type_code");

                    b.Property<int?>("EstablishmentTypeGroupCode")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_type_group_code");

                    b.Property<string>("EstablishmentTypeGroupName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("establishment_type_group_name");

                    b.Property<string>("EstablishmentTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("establishment_type_name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("LaCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("la_code")
                        .IsFixedLength();

                    b.Property<string>("LaName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("la_name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Locality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postcode")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("town")
                        .UseCollation("case_insensitive");

                    b.Property<int?>("Urn")
                        .HasMaxLength(6)
                        .HasColumnType("integer")
                        .HasColumnName("urn")
                        .IsFixedLength();

                    b.HasKey("EstablishmentId")
                        .HasName("pk_establishments");

                    b.HasIndex("Urn")
                        .HasDatabaseName("ix_establishment_urn");

                    b.HasIndex("LaCode", "EstablishmentNumber")
                        .HasDatabaseName("ix_establishment_la_code_establishment_number");

                    b.ToTable("establishments", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<DateTime>("Inserted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserted");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_events_key")
                        .HasFilter("key is not null");

                    b.HasIndex("Payload")
                        .HasDatabaseName("ix_events_payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("PersonId", "EventName")
                        .HasDatabaseName("ix_events_person_id_event_name")
                        .HasFilter("person_id is not null");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("PersonId", "EventName"), new[] { "Payload" });

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.JourneyState", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("instance_id");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("InstanceId")
                        .HasName("pk_journey_states");

                    b.ToTable("journey_states", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.NameSynonyms", b =>
                {
                    b.Property<long>("NameSynonymsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("name_synonyms_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NameSynonymsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.Property<string[]>("Synonyms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("synonyms")
                        .UseCollation("case_insensitive");

                    b.HasKey("NameSynonymsId")
                        .HasName("pk_name_synonyms");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_name_synonyms_name");

                    b.ToTable("name_synonyms", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.OneLoginUser", b =>
                {
                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FirstOneLoginSignIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_one_login_sign_in");

                    b.Property<DateTime?>("FirstSignIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_sign_in");

                    b.Property<string>("LastCoreIdentityVc")
                        .HasColumnType("jsonb")
                        .HasColumnName("last_core_identity_vc");

                    b.Property<DateTime>("LastOneLoginSignIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_one_login_sign_in");

                    b.Property<DateTime?>("LastSignIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in");

                    b.Property<int>("MatchRoute")
                        .HasColumnType("integer")
                        .HasColumnName("match_route");

                    b.Property<string>("MatchedAttributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("matched_attributes");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int?>("VerificationRoute")
                        .HasColumnType("integer")
                        .HasColumnName("verification_route");

                    b.Property<string>("VerifiedDatesOfBirth")
                        .HasColumnType("jsonb")
                        .HasColumnName("verified_dates_of_birth");

                    b.Property<string>("VerifiedNames")
                        .HasColumnType("jsonb")
                        .HasColumnName("verified_names");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_on");

                    b.HasKey("Subject")
                        .HasName("pk_one_login_users");

                    b.ToTable("one_login_users", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_address")
                        .UseCollation("case_insensitive");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("NationalInsuranceNumber")
                        .HasMaxLength(9)
                        .HasColumnType("character(9)")
                        .HasColumnName("national_insurance_number")
                        .IsFixedLength();

                    b.Property<string>("Trn")
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("trn")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("PersonId")
                        .HasName("pk_persons");

                    b.HasIndex("Trn")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_trn")
                        .HasFilter("trn is not null");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.PersonEmployment", b =>
                {
                    b.Property<Guid>("PersonEmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("person_employment_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer")
                        .HasColumnName("employment_type");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<DateOnly>("LastExtractDate")
                        .HasColumnType("date")
                        .HasColumnName("last_extract_date");

                    b.Property<DateOnly>("LastKnownEmployedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_known_employed_date");

                    b.Property<string>("NationalInsuranceNumber")
                        .HasMaxLength(9)
                        .HasColumnType("character(9)")
                        .HasColumnName("national_insurance_number")
                        .IsFixedLength();

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PersonPostcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("person_postcode");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("PersonEmploymentId")
                        .HasName("pk_person_employments");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_person_employments_establishment_id");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_person_employments_key");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_person_employments_person_id");

                    b.ToTable("person_employments", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.PersonSearchAttribute", b =>
                {
                    b.Property<long>("PersonSearchAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("person_search_attribute_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PersonSearchAttributeId"));

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attribute_key")
                        .UseCollation("case_insensitive");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attribute_type")
                        .UseCollation("case_insensitive");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("attribute_value")
                        .UseCollation("case_insensitive");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("PersonSearchAttributeId")
                        .HasName("pk_person_search_attributes");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_person_search_attributes_person_id");

                    b.HasIndex("AttributeType", "AttributeValue")
                        .HasDatabaseName("ix_person_search_attributes_attribute_type_and_value");

                    b.ToTable("person_search_attributes", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.SupportTask", b =>
                {
                    b.Property<string>("SupportTaskReference")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("support_task_reference");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("OneLoginUserSubject")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("one_login_user_subject");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SupportTaskType")
                        .HasColumnType("integer")
                        .HasColumnName("support_task_type");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<JsonDocument>("_data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.HasKey("SupportTaskReference")
                        .HasName("pk_support_tasks");

                    b.HasIndex("OneLoginUserSubject")
                        .HasDatabaseName("ix_support_tasks_one_login_user_subject");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_support_tasks_person_id");

                    b.ToTable("support_tasks", (string)null);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.UserBase", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("user_type");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<int>("UserType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.SystemUser", b =>
                {
                    b.HasBaseType("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.UserBase");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a81394d1-a498-46d8-af3e-e077596ab303"),
                            Active = true,
                            Name = "System",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.User", b =>
                {
                    b.HasBaseType("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.UserBase");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email")
                        .UseCollation("case_insensitive");

                    b.Property<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("varchar[]")
                        .HasColumnName("roles");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.OneLoginUser", b =>
                {
                    b.HasOne("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.OneLoginUser", "PersonId")
                        .HasConstraintName("fk_one_login_users_persons_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.PersonEmployment", b =>
                {
                    b.HasOne("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_employments_establishment_id");

                    b.HasOne("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_employments_person_id");
                });

            modelBuilder.Entity("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.SupportTask", b =>
                {
                    b.HasOne("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.OneLoginUser", null)
                        .WithMany()
                        .HasForeignKey("OneLoginUserSubject")
                        .HasConstraintName("fk_support_tasks_one_login_user");

                    b.HasOne("Dfe.Sww.Ecf.Core.DataStore.Postgres.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .HasConstraintName("fk_support_tasks_person");
                });
#pragma warning restore 612, 618
        }
    }
}
