services:
  moodleapp:
    build:
      context: ./moodle-docker
    image: moodle-web:1.0
    container_name: moodle-web
    ports:
      - 8080:80
    env_file:
      - "development.env"
    volumes:
      - moodledata:/var/www/moodledata
      - ${PWD}/moodle-docker/config.php:/var/www/html/config.php
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    env_file:
      - "development.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -p 5432 -U $$POSTGRES_USER -d $$POSTGRES_DB",
        ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
  moodledata:
