module "db-jobs-app" {
  source                                = "./modules/function-app"
  environment                           = var.environment
  location                              = var.azure_region
  resource_group                        = module.stack.resource_group_name
  resource_name_prefix                  = var.resource_name_prefix
  function_app_name                     = "${var.resource_name_prefix}-fa-db-jobs"
  acr_name                              = var.acr_name
  acr_id                                = local.acr_id
  service_plan_id                       = module.stack.db_jobs_service_plan_id
  tags                                  = local.common_tags
  docker_image_name                     = "dfe-digital/nothing:latest"
  storage_account_name                  = module.stack.file_storage_account_name
  storage_account_access_key            = module.stack.file_storage_access_key
  appinsights_connection_string         = module.stack.appinsights_connection_string
  health_check_path                     = "/api/health"
  subnet_functionapp_id                 = module.stack.subnet_functionapp_id
  virtual_network_name                  = module.stack.vnet_name
  virtual_network_id                    = module.stack.vnet_id
  key_vault_id                          = module.stack.kv_id
  function_worker_runtime               = "dotnet-isolated"
  subnet_functionapp_privateendpoint_id = module.stack.subnet_functionapp_privateendpoint_id
  private_dns_zone_id                   = module.stack.private_dns_zone_id
  app_settings = merge({
    "CONNECTIONSTRINGS__DEFAULTCONNECTION" = "Host=${module.stack.postgres_db_host};Username=${module.stack.postgres_username};"
    "STORAGECONNECTIONSTRING"              = "https://${module.stack.db_backup_blob_storage_account_name}.blob.core.windows.net/[SA_REPLACE_CONTAINER]"
    "DB_PASSWORD"                          = "@Microsoft.KeyVault(SecretUri=${module.stack.full_postgres_secret_password_uri})"
  }, var.db_jobs_app_settings)
}
