# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0-appservice AS notification-api
WORKDIR /home/site/wwwroot
EXPOSE 8080

COPY DfeSwwEcf.NotificationService/bin/Release/net8.0/publish/ .

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    FUNCTIONS_WORKER_RUNTIME=dotnet-isolated \
    DOTNET_CMD="dotnet"

ENTRYPOINT ["dotnet", "DfeSwwEcf.NotificationService.dll"]

# Install SSH Server for Kudu
# RUN apt-get update && apt-get install -y openssh-server sudo
#  \
#     shadow \
#     su-exec

# Support kudu tools SSH for remote debug
# COPY sshd_config /etc/ssh/sshd_config
# RUN --mount=type=secret,id=AZURE_KUDU_SSH_PASSWORD \
#     export AZURE_KUDU_SSH_PASSWORD=$(cat /run/secrets/AZURE_KUDU_SSH_PASSWORD) \
#     && echo "$AZURE_KUDU_SSH_USER:$AZURE_KUDU_SSH_PASSWORD" | chpasswd \
#     && > /etc/motd \
#     && mkdir -p /var/run/sshd \
#     && chmod 0755 /var/run/sshd \
#     && ssh-keygen -A

# WORKDIR /App

# ARG AZURE_KUDU_SSH_USER

# COPY entry-point.sh ./entry-point.sh
# RUN chmod +x entry-point.sh

# RUN chown -R app:app /App

# ENTRYPOINT ["/App/entry-point.sh"]
