# syntax=docker/dockerfile:1
# Base image for the Azure Functions runtime for .NET 8
FROM mcr.microsoft.com/azure-functions/dotnet:4-dotnet8.0 AS notification-api
WORKDIR /home/site/wwwroot
EXPOSE 80

COPY DfeSwwEcf.NotificationService/bin/Release/net8.0/publish/ .

# Install SSH Server for Kudu
RUN apk --no-cache add openssh \
    shadow \
    su-exec

# Support kudu tools SSH for remote debug
COPY sshd_config /etc/ssh/sshd_config
RUN --mount=type=secret,id=AZURE_KUDU_SSH_PASSWORD \
    export AZURE_KUDU_SSH_PASSWORD=$(cat /run/secrets/AZURE_KUDU_SSH_PASSWORD) \
    && echo "$AZURE_KUDU_SSH_USER:$AZURE_KUDU_SSH_PASSWORD" | chpasswd \
    && > /etc/motd \
    && mkdir -p /var/run/sshd \
    && chmod 0755 /var/run/sshd \
    && ssh-keygen -A

WORKDIR /App

ARG AZURE_KUDU_SSH_USER

COPY entry-point.sh ./entry-point.sh
RUN chmod +x entry-point.sh

RUN chown -R app:app /App

ENTRYPOINT ["/App/entry-point.sh"]
