set shell := ["bash", "-e", "-o", "pipefail", "-c"]

solution-root := "."

default:
  @just --list

# Install local tools
install-tools:
  @cd {{solution-root}} && dotnet tool restore
  # We need to copy the bin folder, the .dockerignore makes it inaccessible
  @rm .dockerignore

# Restore dependencies
restore:
  @cd {{solution-root}} && dotnet restore
  
# Build the .NET solution
build:
  @cd {{solution-root}} && dotnet build --no-restore

# Test the .NET solution
#test:
#  @cd {{solution-root}} && dotnet test

# Publish the project
package-component:
  @dotnet publish {{solution-root}} -c Release --no-restore
