#!/bin/bash
# .ddev/commands/web/set-permissions
# This command sets permissions for scripts in the web container 
# Usage:
#   ddev set-permissions   
set -e

# Make the following scripts executable
chmod +x /var/www/html/scripts/install-moosh
echo "Permissions updated for /var/www/html/scripts/install-moosh"

chmod +x /var/www/html/scripts/install-oidc-plugin
echo "Permissions updated for /var/www/html/scripts/install-oidc-plugin"
