version: '3.8'

services:
    web:
        build: .
        ports:
            - "8585:8585"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_URLS: "http://+:8585"
