# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0-appservice AS db-operations-service
WORKDIR /home/site/wwwroot

ENV WEBSITES_PORT=8080

EXPOSE 8080

COPY DfeSwwEcf.DbOperationsService/bin/Release/net8.0/publish/ .

# RUN apt-get update && apt-get install -y \
#     postgresql-client \
#     && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    postgresql-client \
    python3-pip \
    build-essential \
    libffi-dev \
    python3-dev && \
    pip3 install --break-system-packages azure-cli && \
    apt-get remove -y build-essential libffi-dev python3-dev && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY run-backup.sh /app/scripts/
COPY run-restore.sh /app/scripts/
RUN chmod +x /app/scripts/*.sh

# Update PATH to include the scripts directory
ENV PATH="${PATH}:/app/scripts"

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    FUNCTIONS_WORKER_RUNTIME=dotnet-isolated \
    DOTNET_CMD="dotnet"
