#!/bin/bash
# /var/www/html/scripts/install-moosh
# This bash script downloads and installs moosh shell plugin in the tmp directory. 
# Usage:
#   /var/www/html/scripts/install-moosh        

set -e

# Clone Moosh repository
git clone https://github.com/tmuras/moosh.git /tmp/moosh

# Install Moosh
cd /tmp/moosh
composer install

# Make Moosh globally available
ln -s /tmp/moosh/moosh.php /usr/local/bin/moosh
