set shell := ["pwsh", "-nop", "-c"]

solution-root := "Dfe.Sww.Ecf"
user-secrets-id := "Dfe.Sww.Ecf"
cli-user-secrets-id := "Dfe.Sww.Ecf.Cli"
test-user-secrets-id := "Dfe.Sww.EcfTests"

mod onelogin-sim

default:
  @just --list

# Install local tools
install-tools:
  @cd {{solution-root}} && dotnet tool restore
  npm install -g sass

# Restore dependencies
restore:
  @cd {{solution-root}} && dotnet restore
  @cd {{solution-root / "src" / "Dfe.Sww.Ecf.AuthorizeAccess" }} && dotnet libman restore --verbosity quiet

# Run the ecfcli
cli *ARGS:
  @cd {{solution-root / "src" / "Dfe.Sww.Ecf.Cli"}} && dotnet {{"bin" / "Debug" / "net8.0" / "ecfcli.dll"}} {{ARGS}}

# Build the .NET solution
build:
  @cd {{solution-root}} && dotnet build

build-project project:
  @dotnet build {{solution-root}}/src/{{project}}

# Test the .NET solution
test:
  @cd {{solution-root}} && dotnet test

# Format the .NET solution and Terraform code
format:
  @cd {{solution-root}} && dotnet format
  @terraform fmt terraform/aks

# Format any un-committed .tf or .cs files
format-changed:
  #!pwsh -nop

  function Get-ChangedFiles {
    param (
      $Path
    )

    (git status --porcelain $Path) | foreach { $_.substring(3) } | Where-Object { Test-Path $_ }
  }

  $changedTfFiles = Get-ChangedFiles "terraform/*.tf"
  foreach ($tf in $changedTfFiles) {
    terraform fmt $tf
  }

  $changedCsFiles = (Get-ChangedFiles "{{solution-root}}/**/*.cs") | foreach { $_ -Replace "^{{solution-root}}/", "" }
  if ($changedCsFiles.Length -gt 0) {
    $dotnetArgs = @("format", "--no-restore", "--include") + $changedCsFiles
    cd {{solution-root}} && dotnet $dotnetArgs
  }

# Run the EF Core Command-line Tools for the Core project
ef *ARGS:
  @cd {{solution-root / "src" / "Dfe.Sww.Ecf.Core"}} && dotnet dotnet-ef {{ARGS}}

# Run the AuthorizeAccess project in Development mode and watch for file changes
watch-authz:
  @cd {{solution-root / "src" / "Dfe.Sww.Ecf.AuthorizeAccess"}} && dotnet watch

publish:
  @cd {{solution-root}} && dotnet publish -c Release --no-restore

publish-project project:
  @dotnet publish {{solution-root}}/src/{{project}} -c Release --no-restore

# Build the Docker image
docker-build *ARGS: install-tools restore
  @cd {{solution-root}} && dotnet publish -c Release --no-restore
  @cd {{solution-root}} && docker build . {{ARGS}}

set-db-connection value:
  @dotnet user-secrets set ConnectionStrings:DefaultConnection "{{value}}" --id {{user-secrets-id}}
  @dotnet user-secrets set ConnectionStrings:DefaultConnection "{{value}}" --id {{cli-user-secrets-id}}

set-test-db-connection value:
  @dotnet user-secrets set ConnectionStrings:DefaultConnection "{{value}}" --id {{test-user-secrets-id}}
  @dotnet user-secrets set ConnectionStrings:TestDbConnection "{{value}}" --id {{cli-user-secrets-id}}

# Set a configuration entry in user secrets for running the apps
set-secret key value:
  @dotnet user-secrets set "{{key}}" "{{value}}" --id {{user-secrets-id}}

# Set a configuration entry in user secrets for tests
set-tests-secret key value:
  @dotnet user-secrets set "{{key}}" "{{value}}" --id {{test-user-secrets-id}}

create-admin email name:
  @cd {{solution-root / "src" / "Dfe.Sww.Ecf.Cli"}} && dotnet {{"bin" / "Debug" / "net8.0" / "ecfcli.dll"}} create-admin --email {{email}} --name {{quote(name)}}

make *ARGS:
  @make {{ARGS}}

# Removes the cached DB schema version file for tests
remove-tests-schema-cache:
  @scripts/Remove-TestsSchemaCache.ps1
