name: DevOps Workflow

on:
  push:
    branches:
      - infra/terraform-dev-kash
  workflow_dispatch:  # <-- This allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello
        run: echo "Hello from DevOps workflow!"

