
ARG FULL_MOODLE_IMAGE_VERSION

# The install image is based off exactly the same image as the Moodle image
FROM ${FULL_MOODLE_IMAGE_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client

COPY entry-point-azure-install.sh /app/entry-point.sh
