# Stage 1: Build the custom Moodle image components
FROM moodlehq/moodle-php-apache:8.3-bookworm AS builder

# Install tools needed for cloning, downloading, and unzipping.
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    unzip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Download and extract the theme.
ARG GITHUB_RELEASE_URL="https://github.com/DFE-Digital/govuk-moodle-theme/releases/download/2024200800/govuk-moodle-theme.zip"
RUN curl -L -o govuk-moodle-theme.zip "$GITHUB_RELEASE_URL" && \
    unzip govuk-moodle-theme.zip -d theme

# Clone the Moodle source code.
RUN git clone -b MOODLE_405_STABLE --single-branch --depth=1 git://git.moodle.org/moodle.git

# Copy custom config.php into the correct location
COPY ./config.php ./moodle/config.php
# Re-enable if DB connectivity tracing is required
#COPY ./dmllib.trace.php ./moodle/lib/dmllib.php

# Prune folders and files beginning with '.' as well as other non-essential files
RUN find ./moodle -mindepth 1 -type d -name '.*' -exec rm -rf {} + && \
    find ./moodle -type f \( -name ".*" -o -name "*.js" -o -name "*.txt" -o -name -o -name "*.md" -o -name "*.dist" -o -name "*.lock" \) -delete && \
    rm -f ./moodle/*.json && \
    rm -f ./moodle/config-dist.php

# Stage 2: Final custom Moodle image
# Use the [official Moodle PHP-apache image](https://github.com/moodlehq/moodle-php-apache) as a base
FROM moodlehq/moodle-php-apache:8.3-bookworm

WORKDIR /var/www/html

# Copy the pruned Moodle source / downloaded theme
COPY --from=builder --chown=www-data:www-data /build/moodle/ ./
COPY --from=builder --chown=www-data:www-data /build/theme/govuk/ ./theme/

# Needs to run as root for various standard mount point permissions in Azure
# Apache is configured to run as www-data
USER root

CMD ["apache2-foreground"]

EXPOSE 80
