#!/bin/bash
# .ddev/commands/web/install-theme
# This command updates the govuk theme for Moodle.
# It downloads and installs a govuk theme release.
# Usage:
#   ddev install-theme           # Fetches the latest release by default
#   ddev install-theme "v0.1.0"  # Uses the specified release version
#
# The script then updates config.php to set the theme to govuk and purges Moodle caches.

set -e

REPO="DFE-Digital/govuk-moodle-theme"

LATEST_RELEASE=$(curl --silent -m 10 --connect-timeout 5 "https://api.github.com/repos/${REPO}/releases/latest")

LATEST_TAG=$(echo "$LATEST_RELEASE" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

# Default release if no argument is provided.
if [[ "$1" == "" || "$1" == "default" ]]; then
  RELEASE=$LATEST_TAG
else
  RELEASE=$1
fi

THEME_URL="https://github.com/${REPO}/releases/download/${RELEASE}/govuk-moodle-theme.zip"

echo "Downloading and installing govuk theme release ${RELEASE} from ${THEME_URL}..."
rm -rf /tmp/theme
curl -L -o /tmp/govuk-moodle-theme.zip "$THEME_URL"
unzip -o /tmp/govuk-moodle-theme.zip -d /tmp/theme

# Remove the old govuk directory if it exists
if [ -d "/var/www/html/public/theme/govuk" ]; then
  rm -rf /var/www/html/public/theme/govuk
fi

mkdir -p /var/www/html/public/theme
mv /tmp/theme/govuk/ /var/www/html/public/theme/govuk
rm -rf /tmp/govuk-moodle-theme.zip /tmp/theme
echo "Govuk theme updated to release ${RELEASE}."

# For Azure, we want the ability to copy the theme but delay the upgrade til deployment
if [[ "$2" != "--copy-only" ]]; then
  echo "Running Moodle upgrade..."
  php public/admin/cli/upgrade.php --non-interactive

  echo "Purging Moodle caches..."
  php public/admin/cli/purge_caches.php
fi

echo "Theme install complete."
