name: Auth unit test

on:
  workflow_dispatch:
  push:
    branches: 
      - SWIP-905-fix-auth-service-unit-test-running-in-ci

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        project_short_name:
          - AuthorizeAccess.Tests
          - Core.Tests
          - UiCommon.Tests
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: swpdp
          POSTGRES_DB: swpdp
        options: >-
          --name postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v5

      - uses: extractions/setup-just@v3

      - name: Install tools
        run: just install-tools
        working-directory: apps/auth-service

      - name: Restore
        run: just ci-restore
        working-directory: apps/auth-service

      - name: Run tests
        shell: bash
        working-directory: apps/auth-service/Dfe.Sww.Ecf/tests/Dfe.Sww.Ecf.${{ matrix.project_short_name }}
        run: |
          dotnet test -e ConnectionStrings__DefaultConnection="Host=localhost;Username=postgres;Password=swpdp;Database=swpdp"
        timeout-minutes: 30
