name: Auth unit test

on:
  workflow_dispatch:
  push:
    branches:
      - SWIP-905-fix-auth-service-unit-test-running-in-ci

jobs:
  tests:
    name: Tests (shared DB)
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: swpdp
          POSTGRES_DB: swpdp
        options: >-
          --name postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      CONNECTION_STRING: Host=localhost;Username=postgres;Password=swpdp;Database=swpdp

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: extractions/setup-just@v3

      - name: Install tools
        run: just install-tools
        working-directory: apps/auth-service

      - name: Restore
        run: just ci-restore
        working-directory: apps/auth-service

      - name: Discover and run tests sequentially (shared DB)
        shell: bash
        working-directory: apps/auth-service
        run: |
          set -euo pipefail

          # Find all *Tests.csproj under the tests folder
          mapfile -t TEST_PROJECTS < <(find . -path "./Dfe.Sww.Ecf/tests/*/*.Tests.csproj" | sort)

          echo "Found test projects:"
          printf ' - %s\n' "${TEST_PROJECTS[@]}"

          for csproj in "${TEST_PROJECTS[@]}"; do
            proj_dir="$(dirname "$csproj")"
            echo "::group::dotnet test $proj_dir"
            dotnet test "$proj_dir" -e ConnectionStrings__DefaultConnection="$CONNECTION_STRING"
            echo "::endgroup::"
          done
