name: Auth unit test

on:
  workflow_dispatch:
  push:
    branches: 
      - SWIP-905-fix-auth-service-unit-test-running-in-ci

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04  # Important - later versions of ubuntu have a different .NET SDK which breaks trscli. Review on .NET 9 upgrade
    strategy:
      fail-fast: false
      matrix:
        project_short_name:
          - AuthorizeAccess.Tests
          - Core.Tests
          - UiCommon.Tests
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: swpdp
          POSTGRES_DB: swpdp
        options: >-
          --name postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v5

      - uses: extractions/setup-just@v3

      - name: Install tools
        run: just install-tools
        working-directory: apps/auth-service

      - name: Restore
        run: just ci-restore
        working-directory: apps/auth-service

      - name: Build project
        run: dotnet build -c Release --no-restore
        working-directory: apps/auth-service/Dfe.Sww.Ecf/tests/Dfe.Sww.Ecf.${{ matrix.project_short_name }}

      - name: Run tests
        uses: ./.github/actions/test
        with:
          test_project_path: apps/auth-service/Dfe.Sww.Ecf/tests/Dfe.Sww.Ecf.${{ matrix.project_short_name }}
          dotnet_test_args: >-
            --no-build
            -e ConnectionStrings__DefaultConnection="Host=localhost;Username=postgres;Password=swpdp;Database=swpdp"
        timeout-minutes: 30