name: "Backup or Restore a database"

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: "The job to run (backup or restore)"
        required: true
        type: choice
        options:
          - backup
          - restore
      db_name:
        description: "The name of the database to backup/restore"
        required: true
        type: choice
        options:
          - moodle
          - authservice
      backup_file_name:
        description: "The name of the backup file in Blob Storage to restore (only for restore jobs)"
        required: false
        type: string
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02
          - d03

jobs:
  map_variables:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      db_instance: ${{ steps.map_name.outputs.db_name }}
      sa_container_name: ${{ steps.map_container.outputs.sa_container_name}}

    steps:
      - name: Map service to actual DB instance
        id: map_name
        run: |
          DB_INSTANCE = ""
          case "${{ github.event.inputs.db_name }}" in
            moodle)
              DB_INSTANCE="s205${{ (github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}_db_moodle_primary"
              ;;
            authservice)
              DB_INSTANCE="s205${{ (github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}_db_auth_service"
              ;;
          esac
          echo "db_instance=$DB_INSTANCE" >> $GITHUB_OUTPUT

      - name: Map storage container name
        id: map_container
        run: |
          SA_CONTAINER = ""
          case "${{ github.event.inputs.db_name }}" in
            moodle)
              SA_CONTAINER="s205${{ (github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-moodle-backups"
              ;;
            authservice)
              SA_CONTAINER="s205${{ (github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-usermanagement-backups
              ;;
            esac
            echo "sa_container_name=$SA_CONTAINER" >> $GITHUB_OUTPUT

  db-backup-restore:
    uses: ./.github/workflows/db-backup-restore.yml
    needs: map_variables
    permissions:
      id-token: write
      contents: read
    with:
      job_to_run: ${{ github.event.inputs.job_to_run }}
      db_name: ${{ needs.map_variables.outputs.db_instance }}
      backup_file_name: ${{ github.event.inputs.backup_file_name }}
      instance: ${{ inputs.instance }}
      storage-account-name: "s205${{inputs.instance}}sabackups"
      storage-container-name: ${{ needs.map_variables.outputs.sa_container_name}} 
    secrets: inherit
