name: Build Image and Publish to ACR

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      branch:
        type: string
        required: true
      checked-out-sha:
        type: string
        required: true
      docker-build-file:
        type: string
        required: true
      org-name:
        type: string
        required: true
      docker-image-name:
        type: string
        required: true

    outputs:
      dockerImageTag:
        description: "The image written to the ACR"
        value: ${{ jobs.build-image.outputs.dockerImageTag }}

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    name: Build & Publish Image
    # Permissions for OIDC authentication
    permissions:
      id-token: write
      contents: write
      issues: write
    outputs:
      dockerImageTag: ${{ steps.image.outputs.dockerImageTag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: Azure Container Registry Login
        run: az acr login --name ${{ vars.IMAGE_REGISTRY_NAME }}
        env:
          ACR_NAME: ${{ vars.IMAGE_REGISTRY_NAME }}

      - name: Format branch name
        run: |
          branchName=${{ inputs.branch }}
          echo FORMATTED_BRANCH_NAME="${branchName//\//-}" >> $GITHUB_ENV

      - name: "Build the image and deploy to ACR"
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ inputs.docker-build-file }}
          build-args: COMMIT_SHA=${{ inputs.checked-out-sha }}
          tags: |
            ${{ vars.IMAGE_REGISTRY_NAME }}/${{ inputs.org-name }}/${{ inputs.docker-image-name }}:${{ env.FORMATTED_BRANCH_NAME }}-${{ inputs.checked-out-sha }}
            ${{ vars.IMAGE_REGISTRY_NAME }}/${{ inputs.org-name }}/${{ inputs.docker-image-name }}:latest
          push: true

      - name: Output Docker Image Tag
        id: image
        run: echo "dockerImageTag=${{ vars.IMAGE_REGISTRY_NAME }}/${{ inputs.org-name }}/${{ inputs.docker-image-name }}:${{ env.FORMATTED_BRANCH_NAME }}-${{ inputs.checked-out-sha }}" >> $GITHUB_OUTPUT
