name: Build Moodle apps (optionally deploy to non-prod)

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.instance }}
  cancel-in-progress: true

jobs:
  build-and-publish-moodle-image:
    name: Build and Publish Moodle Image
    uses: ./.github/workflows/build-and-publish-image.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/moodle-apps-azure
      docker-image-name: wa-moodle
      base-image-version: "${{ vars.MOODLE_BRANCH_VERSION }}"
      build-args: "AZURE_KUDU_SSH_USER=${{ vars.AZURE_KUDU_SSH_USER }};MOODLE_BRANCH_VERSION=${{ vars.MOODLE_BRANCH_VERSION }};MOODLE_GOV_UK_THEME_VERSION=${{ vars.MOODLE_GOV_UK_THEME_VERSION }}"
      build-secrets: "AZURE_KUDU_SSH_PASSWORD"
      build-target: moodle-app

  optional-deploy-moodle-app:
    needs: build-and-publish-moodle-image
    if: ${{ github.event.inputs.instance != 'None' }}
    name: Deploy Moodle App (optional)
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/moodle-apps-azure
      # These are app settings which are required to run the Moodle db update
      fetch-web-app-settings: "MOODLE_DOCKER_WEB_HOST;MOODLE_ADMIN_PASSWORD;POSTGRES_PASSWORD"
      # The app service is used to deploy db migrations after the publish
      execute-migrations-after-deploy: 'true'
      app-service-resource-group: ${{ needs.build-and-publish-moodle-image.outputs.dev-resource-name-prefix }}-swip-rg
      web-app-name: ${{ needs.build-and-publish-moodle-image.outputs.dev-resource-name-prefix }}-wa-moodle-primary
      image-tag: ${{ needs.build-and-publish-moodle-image.outputs.docker-image-tag }}
      version-endpoint-path: /version.txt

  optional-deploy-moodle-cron-app:
    needs: build-and-publish-moodle-image
    if: ${{ github.event.inputs.instance != 'None' }}
    name: Deploy Moodle Cron App (optional)
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      app-service-resource-group: ${{ needs.build-and-publish-moodle-image.outputs.dev-resource-name-prefix }}-swip-rg
      web-app-name: ${{ needs.build-and-publish-moodle-image.outputs.dev-resource-name-prefix }}-wa-moodle-cron
      image-tag: ${{ needs.build-and-publish-moodle-image.outputs.docker-image-tag }}
      version-endpoint-path: /version.txt
