name: Build user management (optionally deploy to non-prod)
run-name: >-
  Build user management
  ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.instance != 'None' && format('and deploy to {0}', inputs.instance) ||
     github.event_name == 'pull_request' && format('for PR #{0}', github.event.number) ||
     github.event_name == 'push' && 'and deploy to d01 (merge to dev)' || '' }}

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02
          - d03
          - d04
  pull_request:
    branches:
      - development
    paths:
      - "apps/user-management/**"
  push:
    branches:
      - development
    paths:
      - "apps/user-management/**"

concurrency:
  # Unique group for workflow_dispatch AND unique group for each PR/Push
  group: ${{ (github.event_name == 'pull_request' || github.event_name == 'push') && format('{0}-{1}', github.workflow, github.ref) || format('{0}-{1}', github.workflow, github.event.inputs.instance) }}
  cancel-in-progress: true

jobs:
  build-and-publish-user-management-image:
    name: Build and Publish User Management Image
    uses: ./.github/workflows/build-and-publish-image.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/user-management/apps/frontend
      # Path is in relation to the working directory
      docker-build-file: Dockerfile-azure
      docker-image-name: user-management
      build-args: "AZURE_KUDU_SSH_USER=${{ vars.AZURE_KUDU_SSH_USER }}"
      build-secrets: "AZURE_KUDU_SSH_PASSWORD"
      build-target: user-management
      publish-image: ${{ github.event_name != 'pull_request' }}

  optional-deploy-user-anageent:
    needs: build-and-publish-user-management-image
    if: ${{ (github.event.inputs.instance != 'None' && github.event.inputs.instance) || github.event_name == 'push' }}
    name: Deploy User Management (optional)
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/user-management/apps/frontend
      app-service-resource-group: ${{ needs.build-and-publish-user-management-image.outputs.dev-resource-name-prefix }}-swip-rg
      web-app-name: ${{ needs.build-and-publish-user-management-image.outputs.dev-resource-name-prefix }}-wa-user-management
      image-tag: ${{ needs.build-and-publish-user-management-image.outputs.docker-image-tag }}
      version-endpoint-path: /version.txt
