name: Build proxy service (optionally deploy to non-prod)
run-name: Build proxy service ${{ github.event.inputs.instance && github.event.inputs.instance != 'None' && format('and deploy to {0}', inputs.instance) || format('') }}

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance for deployment"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02
          - d03
  pull_request:
    branches:
      - main
    paths:
      - "apps/proxy-app-azure/**"

concurrency:
  # Unique group for workflow_dispatch AND unique group for each PR
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.ref) || format('{0}-{1}', github.workflow, github.event.inputs.instance) }}
  cancel-in-progress: true

jobs:
  build-and-publish-proxy-image:
    name: Build and Publish Proxy Image
    uses: ./.github/workflows/build-and-publish-image.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/proxy-app-azure
      docker-image-name: proxy-service
      build-args: "AZURE_KUDU_SSH_USER=${{ vars.AZURE_KUDU_SSH_USER }}"
      build-secrets: "AZURE_KUDU_SSH_PASSWORD"
      build-target: proxy-service
      publish-image: ${{ github.event_name != 'pull_request' }}

  optional-deploy-proxy-service:
    needs: build-and-publish-proxy-image
    if: ${{ github.event.inputs.instance != 'None' && github.event.inputs.instance }}
    name: Deploy Proxy Service (optional)
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      app-service-resource-group: ${{ needs.build-and-publish-proxy-image.outputs.dev-resource-name-prefix }}-swip-rg
      web-app-name: ${{ needs.build-and-publish-proxy-image.outputs.dev-resource-name-prefix }}-wa-proxy-service
      image-tag: ${{ needs.build-and-publish-proxy-image.outputs.docker-image-tag }}
      version-endpoint-path: /version.txt
