name: Build Image and Publish to GCR

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      checked-out-sha:
        type: string
        required: true
    outputs:
      dockerImageTag:
        description: "The image written to the GCR"
        value: ${{ jobs.build-image.outputs.dockerImageTag }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: true

env:
  DOCKER_IMAGE: social-work-induction-programme-digital-service
  ORG_NAME: dfe-digital

jobs:
  build-image:
    runs-on: ubuntu-24.04
    name: Build & Publish Image
    outputs:
      dockerImageTag: ${{ steps.image.outputs.dockerImageTag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Format branch name
        run: |
          branchName=${{ inputs.branch }}
          echo FORMATTED_BRANCH_NAME="${branchName//\//-}" >> $GITHUB_ENV

      - name: "Login to ACR"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZ_CLIENT_ID }}
          password: ${{ secrets.AZ_CLIENT_SECRET }}

      - name: "Build the image and deploy to ACR"
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./moodle-docker/Dockerfile
          build-args: COMMIT_SHA=${{ inputs.checked-out-sha }}
          tags: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.ORG_NAME }}/${{ env.DOCKER_IMAGE }}:${{ env.FORMATTED_BRANCH_NAME }}-${{ inputs.checked-out-sha }}
          push: true

      - name: Output Docker Image Tag
        id: image
        run: echo "dockerImageTag=${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.ORG_NAME }}/${{ env.DOCKER_IMAGE }}:${{ env.FORMATTED_BRANCH_NAME }}-${{ inputs.checked-out-sha }}" >> $GITHUB_OUTPUT
