name: Build Notification API (optionally deploy to non-prod)
run-name: >-
  Build Notification API
  ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.instance != 'None' && format('and deploy to {0}', inputs.instance) ||
     github.event_name == 'pull_request' && format('for PR #{0}', github.event.number) ||
     github.event_name == 'push' && 'and deploy to d01 (merge to dev)' || '' }}

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02
          - d03
          - d04
  pull_request:
    branches:
      - development
    paths:
      - "apps/user-management/apps/notification-service/**"
      - "apps/user-management/apps/notification-service-test/**"
  push:
    branches:
      - development
    paths:
      - "apps/user-management/apps/notification-service/**"
      - "apps/user-management/apps/notification-service-test/**"

concurrency:
  # Unique group for workflow_dispatch AND unique group for each PR/Push
  group: ${{ (github.event_name == 'pull_request' || github.event_name == 'push') && format('{0}-{1}', github.workflow, github.ref) || format('{0}-{1}', github.workflow, github.event.inputs.instance) }}
  cancel-in-progress: true

jobs:
  build-and-publish-notifications-api-image:
    name: Build and Publish Notification API Image
    uses: ./.github/workflows/build-and-publish-image.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/user-management/apps/notification-service
      # Path is in relation to the working directory
      docker-build-file: Dockerfile-azure
      docker-image-name: notification-api
      build-args: "AZURE_KUDU_SSH_USER=${{ vars.AZURE_KUDU_SSH_USER }}"
      build-secrets: "AZURE_KUDU_SSH_PASSWORD"
      build-target: notification-api
      publish-image: ${{ github.event_name != 'pull_request' }}

  optional-deploy-notification-service:
    needs: build-and-publish-notifications-api-image
    if: ${{ (github.event.inputs.instance != 'None' && github.event.inputs.instance) || github.event_name == 'push' }}
    name: Deploy Notification API (optional)
    uses: ./.github/workflows/deploy-function-app.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/user-management/apps/notification-service
      app-service-resource-group: ${{ needs.build-and-publish-notifications-api-image.outputs.dev-resource-name-prefix }}-swip-rg
      tunnel-app-service: ${{ needs.build-and-publish-notifications-api-image.outputs.dev-resource-name-prefix }}-wa-proxy-service
      requires-container-registry-login: true
      function-app-name: ${{ needs.build-and-publish-notifications-api-image.outputs.dev-resource-name-prefix }}-fa-notification-service
      image-tag: ${{ needs.build-and-publish-notifications-api-image.outputs.docker-image-tag }}
