name: Build auth service (optionally deploy to non-prod)
run-name: Build auth service ${{ github.event.inputs.instance && github.event.inputs.instance != 'None' && format('and deploy to {0}', inputs.instance) || format('') }}

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02
          - d03
  pull_request:
    branches:
      - development
    paths:
      - "apps/auth-service/**"

concurrency:
  # Unique group for workflow_dispatch AND unique group for each PR
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.ref) || format('{0}-{1}', github.workflow, github.event.inputs.instance) }}
  cancel-in-progress: true

jobs:
  build-and-publish-auth-service-image:
    name: Build and Publish Auth Service Image
    uses: ./.github/workflows/build-and-publish-image.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/auth-service
      # Path is in relation to the working directory
      docker-build-file: ./Dfe.Sww.Ecf/Dockerfile
      docker-image-name: auth-service
      build-args: "AZURE_KUDU_SSH_USER=${{ vars.AZURE_KUDU_SSH_USER }}"
      build-secrets: "AZURE_KUDU_SSH_PASSWORD"
      build-target: auth-service
      publish-image: ${{ github.event_name != 'pull_request' }}
      # Enable auth tests once all running okay locally
      # run-auth-tests: true

  optional-deploy-auth-service:
    needs: build-and-publish-auth-service-image
    if: ${{ github.event.inputs.instance != 'None' && github.event.inputs.instance }}
    name: Deploy Auth Service (optional)
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/auth-service
      # These are app settings which are required to run the db update
      fetch-web-app-settings: "DB_SERVER_NAME;DB_DATABASE_NAME;DB_USER_NAME;DB_PASSWORD"
      app-service-resource-group: ${{ needs.build-and-publish-auth-service-image.outputs.dev-resource-name-prefix }}-swip-rg
      tunnel-app-service: ${{ needs.build-and-publish-auth-service-image.outputs.dev-resource-name-prefix }}-wa-proxy-service
      # Get database server name from the app setting
      tunnel-remote-server-name: "DB_SERVER_NAME"
      tunnel-remote-server-port: 5432
      # DB updates will be performed through the auth service container
      requires-container-registry-login: true
      web-app-name: ${{ needs.build-and-publish-auth-service-image.outputs.dev-resource-name-prefix }}-wa-auth-service
      image-tag: ${{ needs.build-and-publish-auth-service-image.outputs.docker-image-tag }}
      version-endpoint-path: /api/accounts/version
