name: Checkov
on:
  # Only run the terraform linting on PR to development - otherwise wastes build resources
  # as it also runs as part of terraform deploy on any branch
  pull_request:
    branches:
      - development
    paths:
      - 'terraform/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: 3.12

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@84bb9993ad52a967bfc75a42c7a8ea0b8996286a  # v12
        with:
          directory: terraform/
          framework: terraform
          skip_check: CKV2_AZURE_33
