name: Checkov
on:
  # Only run the terraform linting on PR to main - otherwise wastes build resources
  # as it also runs as part of terraform deploy on any branch
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          skip_check: CKV2_AZURE_33
