name: DB backup and restore

on:
  workflow_call:
    inputs:
      job-to-run:
        description: "The job to run (backup or restore)"
        required: true
        type: string
      backup-file-name:
        description: "The name of the backup file in Blob Storage to restore"
        required: false
        type: string
      db-name:
        description: "The name of the database to backup/restore"
        required: true
        type: string
      instance:
        description: "Environment instance"
        type: string
      storage-account-name:
        description: Name of the storage account where the backup files will be stored
        type: string
      storage-container-name:
        description: Name of the storage container for backup files
        type: string
      

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      
permissions:
  id-token: write
  contents: read

jobs:
  backup:
    if: inputs.job-to-run == 'backup'
    runs-on: ubuntu-latest
    env:
      AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      
    steps:
      - name: Log in to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Trigger Backup Job
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp job start \
            --name "s205${{inputs.instance}}-database-jobs-ca" \
            --resource-group "s205${{inputs.instance}}-swip-rg" \
            --command "/usr/local/bin/run-backup.sh ${{ github.event.inputs.db-name }} ${{ github.event.inputs.storage-account-name }} ${{ github.event.inputs.storage-container-name }}"

  restore:
    if: inputs.job-to-run == 'restore'
    runs-on: ubuntu-latest

    steps:
      - name: Check for backup-file-name
        if: inputs.backup-file-name == ''
        run: |
          echo "Error: backup_file_name input is required for the restore job."
          exit 1
      
      - name: Log in to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Trigger Restore job
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp job start \
            --name "s205${{inputs.instance}}-database-jobs-ca" \
            --resource-group "s205${{inputs.instance}}-swip-rg" \
            --command "/usr/local/bin/run-restore.sh ${{ github.event.inputs.db-name }} ${{ github.event.inputs.storage-account-name }} ${{ github.event.inputs.storage-container-name }} ${{ github.event.inputs.backup-file-name }}"
