name: Deploy Moodle App

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02
          - d03
      version-tag:
        description: Version tag to deploy, e.g. 405-20250507.57da7f9.dev
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.instance }}
  cancel-in-progress: true

jobs:
  deploy-moodle-app:
    if: ${{ github.event.inputs.instance != 'None' }}
    name: Deploy Moodle App
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/moodle-apps-azure
      # These are app settings which are required to run the Moodle db update
      fetch-web-app-settings: "MOODLE_DOCKER_WEB_HOST;MOODLE_ADMIN_PASSWORD;POSTGRES_PASSWORD;MOODLE_WEB_SERVICE_USER_PASSWORD;AUTH_SERVICE_CLIENT_SECRET"
      # The app service is used to deploy db migrations after the publish
      execute-migrations-after-deploy: 'true'
      app-service-resource-group: s205${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-swip-rg
      web-app-name: s205${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-wa-moodle-primary
      image-tag: s205d01acr.azurecr.io/dfe-digital-swip-digital-service/wa-moodle:${{ github.event.inputs.version-tag }}
      version-endpoint-path: /version.txt

  deploy-moodle-cron-app:
    if: ${{ github.event.inputs.instance != 'None' }}
    name: Deploy Moodle Cron App
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    with:
      environment: Dev
      environment-instance: ${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}
      app-service-resource-group: s205${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-swip-rg
      web-app-name: s205${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-wa-moodle-cron
      image-tag: s205d01acr.azurecr.io/dfe-digital-swip-digital-service/wa-moodle:${{ github.event.inputs.version-tag }}
      version-endpoint-path: /version.txt
