name: Deploy Function App
description: Deploys an image to an Azure function app service

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      environment-instance:
        type: string
        required: true
      working-dir:
        description: Working directory for just command runner
        type: string

jobs:
  deploy-function-app:
    name: Deploy Function App
    runs-on: ubuntu-24.04
    # Permissions for OIDC Azure authentication (az login)
    permissions:
      id-token: write
      contents: write
      issues: write
    environment: ${{ inputs.environment }}
    env:
      AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      REMOTE_TUNNEL_HOST: ${{ inputs.tunnel-remote-server-name }}
      # This will make the credentials available for remote tunnelling
      AZURE_KUDU_SSH_USER: ${{ vars.AZURE_KUDU_SSH_USER }}
      AZURE_KUDU_SSH_PASSWORD: ${{ secrets.AZURE_KUDU_SSH_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.ref }}

      - name: Log in to Azure CLI
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ env.AZ_CLIENT_ID }}
          tenant-id: ${{ env.AZ_TENANT_ID }}
          subscription-id: ${{ env.AZ_SUBSCRIPTION_ID }}

      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      # Need to retrieve ACR_NAME in particular for next steps
      - name: Load Terraform variables
        uses: ./.github/actions/pre-process-terraform-variables
        with:
          environment: ${{ inputs.environment-instance }}
          add-as-env-vars: true

      - name: Azure Container Registry login
        if: inputs.requires-container-registry-login
        shell: bash
        run: az acr login --name ${{ env.ACR_NAME }}
        env:
          ACR_NAME: ${{ env.ACR_NAME }}

      - name: Deploy function app
        uses: azure/webapps-deploy@2fdd5c3ebb4e540834e86ecc1f6fdcd5539023ee # v3
        with:
          app-name: ${{ inputs.web-app-name }}
          images: "${{ inputs.image-tag }}"
