name: Deploy User Management

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02
          - d03
          - d04
      version-tag:
        description: Version tag to deploy, e.g. 20250506.118df8a.dev
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.instance }}
  cancel-in-progress: true

jobs:
  deploy-user-anageent:
    if: ${{ github.event.inputs.instance != 'None' }}
    name: Deploy User Management
    uses: ./.github/workflows/deploy-app-service.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      environment: Dev
      environment-instance: ${{ (github.event.inputs.instance == 'None' || github.event.inputs.instance == '') && 'd01' || github.event.inputs.instance }}
      working-dir: ./apps/user-management/apps/frontend
      app-service-resource-group: s205${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-swip-rg
      web-app-name: s205${{ (github.event_name == 'push' || github.event.inputs.instance == 'None') && 'd01' || github.event.inputs.instance }}-wa-user-management
      image-tag: s205d01acr.azurecr.io/dfe-digital-swip-digital-service/user-management:${{ github.event.inputs.version-tag }}
      version-endpoint-path: /version.txt
