name: Build Moodle apps (optionally deploy to dev)

on:
  workflow_dispatch:
    inputs:
      deploy_instance:
        description: "Dev environment deployment instance"
        required: true
        default: none - no deploy
        type: choice
        options:
          - none - no deploy
          - primary

jobs:

  create-and-publish-moodle-images:
    name: Create & Publish Moodle Image - Optionally Deploy
    uses: ./.github/workflows/build-moodle-images.yml
    secrets: inherit
    with:
      docker-image-name-moodle: wa-moodle
      docker-image-name-install: wa-install
      base-image-version: "${{ vars.MOODLE_BRANCH_VERSION }}"
      web-app-name-moodle: ${{ github.event.inputs.deploy_instance == 'none - no deploy' && '' || format('wa-moodle-{0}', github.event.inputs.deploy_instance) }}
      web-app-name-install: ${{ github.event.inputs.deploy_instance == 'none - no deploy' && '' || 'wa-moodle-install' }}
      moodle-instance: ${{ github.event.inputs.deploy_instance }}
