name: Build Moodle apps (optionally deploy to dev)

on:
  workflow_dispatch:
    inputs:
      deploy_instance:
        description: "Dev environment deployment instance"
        required: true
        default: none - don't deploy
        type: choice
        options:
          - none - don't deploy
          - primary

jobs:

  create-and-publish-moodle-image:
    name: Create & Publish Moodle Image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      docker-build-folder: ./moodle-docker/
      docker-build-file: Dockerfile-github
      docker-image-name: wa-moodle
      base-image-version: "{{ vars.MOODLE_BRANCH_VERSION }}"

  deploy-moodle-image-to-dev:
    needs: create-and-publish-moodle-image
    name: Deploy Moodle Image To Dev
    if: ${{ inputs.deploy_instance != 'none - don't deploy' }}
    secrets: inherit
    # Permissions for OIDC authentication
    permissions:
      id-token: write
      contents: write
      issues: write
    steps:
      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.create-and-publish-moodle-image.outputs.dev-resource-name-prefix }}-wa-moodle
          images: "${{ needs.create-and-publish-moodle-image.outputs.docker-image-tag }}"

  create-and-publish-moodle-install-image:
    name: Create & Publish Moodle Install Image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      docker-build-folder: ./moodle-docker/
      docker-build-file: Dockerfile-github-install
      docker-image-name: wa-moodle-install
      base-image-version: "{{ vars.MOODLE_BRANCH_VERSION }}"
      build-args: "FULL_MOODLE_IMAGE_VERSION=${{ needs.create-and-publish-moodle-image.outputs.docker-image-tag }}"

  deploy-moodle-install-image-to-dev:
    needs: create-and-publish-moodle-install-image
    name: Deploy Moodle Install Image To Dev
    if: ${{ inputs.deploy_instance != 'none - don't deploy' }}
    secrets: inherit
    # Permissions for OIDC authentication
    permissions:
      id-token: write
      contents: write
      issues: write
    steps:
      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.create-and-publish-moodle-image.outputs.dev-resource-name-prefix }}-wa-moodle-install
          images: "${{ needs.create-and-publish-moodle-install-image.outputs.docker-image-tag }}"

