name: Development build & deploy trace app

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Azure deployment environment"
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Test

jobs:
  create-and-publish-image:
    name: Build & Deploy Trace App
    uses: ./.github/workflows/development-build-and-deploy-template.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      docker-build-file: ./projects/trace-app-docker/Dockerfile
      short-image-name: trace-app
      web-app-name: webapp-trace
