name: Build Moodle apps (optionally deploy to dev)

on:
  workflow_dispatch:
    inputs:
      deploy_instance:
        description: "Dev environment deployment instance"
        required: true
        default: none - no deploy
        type: choice
        options:
          - none - no deploy
          - primary

jobs:

  create-and-publish-moodle-image:
    name: Create & Publish Moodle Image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      docker-build-folder: ./moodle-docker/
      docker-build-file: Dockerfile-github
      docker-image-name: wa-moodle
      base-image-version: "${{ vars.MOODLE_BRANCH_VERSION }}"
      web-app-name: wa-moodle
      deploy-instance: ${{ github.event.inputs.deploy_instance == 'none - no deploy' && '' || github.event.inputs.deploy_instance }}

  create-and-publish-moodle-install-image:
    name: Create & Publish Moodle Install Image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      docker-build-folder: ./moodle-docker/
      docker-build-file: Dockerfile-github-install
      docker-image-name: wa-moodle-install
      base-image-version: "${{ vars.MOODLE_BRANCH_VERSION }}"
      build-args: "FULL_MOODLE_IMAGE_VERSION=${{ needs.create-and-publish-moodle-image.outputs.docker-image-tag }}"
      web-app-name: wa-moodle-install
      deploy-instance: ${{ github.event.inputs.deploy_instance == 'none - no deploy' && '' || github.event.inputs.deploy_instance }}
