name: Development build & deploy Moodle app

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Azure deployment environment"
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Test

      instance:
        description: "Moodle instance to deploy to"
        default: primary
        type: choice
        options:
          - primary

jobs:
  create-and-publish-image:
    name: Build & Deploy Moodle App
    uses: ./.github/workflows/development-build-and-deploy-template.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      docker-build-file: ./projects/moodle-docker/Dockerfile-github
      short-image-name: moodle-app
      web-app-name: webapp-moodle-${{ inputs.instance }}
