name: Development build & deploy trace app

on:
  workflow_dispatch:

jobs:
  create-and-publish-image:
    name: Build & Deploy Trace App
    uses: ./.github/workflows/development-build-and-deploy-template.yml
    secrets: inherit
    with:
      environment: Dev
      docker-build-file: ./trace-app-docker/Dockerfile
      short-image-name: trace-app
      web-app-name: webapp-trace
