name: Build Moodle apps (optionally deploy to non-prod)

on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Environment instance"
        required: true
        default: None
        type: choice
        options:
          - None
          - d01
          - d02

jobs:

  create-and-publish-moodle-images:
    name: Create & Publish Moodle Image - Optionally Deploy
    uses: ./.github/workflows/build-moodle-images.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.instance == 'None' && '' || 'Dev' }}
      environment-instance: ${{ github.event.inputs.instance }}
      docker-image-name-moodle: wa-moodle
      docker-image-name-install: wa-install
      base-image-version: "${{ vars.MOODLE_BRANCH_VERSION }}"
      web-app-name-moodle: ${{ github.event.inputs.instance == 'None' && '' || 'moodle-primary' }}
      web-app-name-install: ${{ github.event.inputs.instance == 'None' && '' || 'moodle-install' }}
      moodle-instance: primary
