name: Validate Dependabot config
on:
  push:
    branches:
      - "SWIP-202-dependency-security-scanning"

jobs:
  validate:
    name: Validate Dependabot config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Validate dependabot.yml
        uses: marocchino/validate-dependabot@3850c9b9e1144268a169f68b5135f395ce102b43 # v1
